apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portworx
  namespace: openshift-gitops
spec:
  destination:
    namespace: portworx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: portworx/
    repoURL: https://github.com/kgonzcar/wordpress
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true