apiVersion: v1
kind: Service
metadata:
  namespace: argo-wp
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: argo-wp
  name: wp
spec:
  host: argo-wp.apps.ocs2.px-test.prlb.flr.c360cloud.com
  port:
    targetPort: 80
  to:
    kind: Service
    name: wordpress
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: demo-sc-shared-manual
provisioner: pxd.portworx.com
parameters:
  #openstorage.io/auth-secret-name: px-user-token
  #openstorage.io/auth-secret-namespace: portworx
  repl: "3"
  priority_io: "high"
  sharedv4: "true"
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: argo-wp
  name: wp-pvc-manual
  annotations:
    volume.beta.kubernetes.io/storage-class: demo-sc-shared-manual
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: argo-wp
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      schedulerName: stork
      containers:
        - image: wordpress:6.2.1-apache
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: WORDPRESS_DB_USER
              value: wordpress
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pvc-manual
