kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: cluster-a
  namespace: portworx
  annotations:
    portworx.io/is-openshift: "true"
    portworx.io/pvc-controller-port: "10261"
    portworx.io/pvc-controller-secure-port: "10262"
    portworx.io/disable-storage-class: "true"
    portworx.io/scc-priority: "2"
spec:
  deleteStrategy:
    type: UninstallAndWipe
  image: portworx/oci-monitor:2.13.7
  imagePullPolicy: IfNotPresent
  security:
    enabled: true
    auth:
      tokenLifetime: '8760h' # 1year
  kvdb:
    internal: true
  cloudStorage:
    deviceSpecs:
      - size=150
    journalDeviceSpec: auto
    kvdbDeviceSpec: size=32
  secretsProvider: k8s
  startPort: 17001
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  csi:
    enabled: true
    installSnapshotController: true
  monitoring:
    telemetry:
      enabled: true
    prometheus:
      enabled: true
      exportMetrics: true
      alertManager:
        enabled: true
  env:
    - name: PURE_FLASHARRAY_SAN_TYPE
      value: "ISCSI"
    - name: PURE_ISCSI_ALLOWED_CIDRS
      value: ""
